### ISSUE TITLE
-[LCCanOpenURL canOpenURL:] deadlocks if called from SpringBoard

### ISSUE THREAD

**Issue by rpetrich** [r-plus/libcanopenurl#1]
If you define overloads for canOpenURL: and canOpenURLString: that call directly into [UIApp canOpenURL:], you avoid the deadlock when people use your API from inside SpringBoard.

**Comment by r-plus** [comment]
Oops. I have forgotten that case. 
Thanks for your report. 

BTW what kind of license AppList is?

**Comment by rpetrich** [comment]
Looks good :+1:

Thanks for the heads up on licensing. I've added LGPL licensing text to the AppList repo.

**Comment by r-plus** [comment]
Thanks for review. 

Okey, I'll inherit that license.

**Comment by rpetrich** [comment]
I consider libcanopenurl sufficiently differentiated from AppList that it need not have the same license if that's what you'd prefer. It's a pretty standard LightMessaging project that happens to use some of the same patterns I use in many of my projects

**Comment by r-plus** [comment]
Sure. I'll keep current MIT license.
