### ISSUE TITLE
Missing from Cydia

### ISSUE THREAD

**Issue by malhal** [r-plus/libcanopenurl#4]
I can't find this package in Cydia but I see listings on BigBoss for it? http://moreinfo.thebigboss.org/moreinfo/depiction.php?file=libcanopenurlDp
Required it for NavigateFromMaps thanks.

**Comment by malhal** [comment]
Probably gone because isn't needed anymore, see issue #3

**Comment by kirb** [comment]
It’s tagged as `cydia::obsolete`, which annoyingly hides it from Cydia. Optimo tends to do that with library packages… Try `apt-cache show jp.r-plus.libcanopenurl` (probably after `apt-get update` because Cydia’s APT cache is separate from the real one now).
